sourceDir: "Path-to-environment" # "/.mounts/labs/simpsonlab/users/dsokolowski/miniconda3/bin/activate" 
externalDir: "Path-to-external-programs" # "/.mounts/labs/simpsonlab/users/dsokolowski/projects/GenomeAnnotationTutorial/external"
dataDir: "Path-to-data-directory" # "/.mounts/labs/simpsonlab/users/dsokolowski/projects/GenomeAnnotationTutorial/data"


# Parameters describing your assembly + annotation
outDir: "path-to-output-directory" # "/.mounts/labs/simpsonlab/users/dsokolowski/projects/AMR_genome_assembly/annotations_masSpec/NMR/Pup3/annotation"
target: "target-assembly-prefix" # "Pup3"
species: "species-name-for-dfamDb" # "heterocephalus_glaber"

assemblyFile: "assembly.fa" # "/.mounts/labs/simpsonlab/users/dsokolowski/projects/NMR_genome_assembly/T2T_March_2025/Pup3/Pup3-NMR.curated.reordered.mt.fa"
MaskedAssemblyFile: "none" # or masked directory to skip earlgrey "/.mounts/labs/simpsonlab/users/dsokolowski/projects/NMR_genome_assembly/T2T_March_2025/Pup3/Pup3.softmasked.fa"
MaskedAssemblyAnnotation: "none" # or repeat bed to skip earlgrey"/.mounts/labs/simpsonlab/users/dsokolowski/projects/NMR_genome_assembly/T2T_March_2025/Pup3/heterocephalus_glaber.filteredRepeats.bed"
rnaseqDir: "/path-to-merged-bams-RNAseq-only/" # or an empty directory if no RNAseq
isoseqDir: "path-to-merged-bams-ISOseq-only" # or an empty directory if no ISOseq
customGFF: "none" # if not none, then it should be the path to your gff file
customRef: "FALSE" # is the custom gff a reference to be upgraded. Switch to "TRUE" if it is a reference.
liftoffRef: "FALSE" # is the gff file from liftOff a reference assembly. Switch to "TRUE" if it is a reference. Note, if you have a custom reference gff then this will be over-written.

# Parameters describing your reference assemblies + annotation

refToga: "Reference-prefix" # "mouse"
TogaDir: "Reference-directory-location" # /.mounts/labs/simpsonlab/users/dsokolowski/projects/GenomeAnnotationTutorial/data/references/mmus_GRC39" # required to bind to singularity image
refTogaFa: "Reference-species-softmasked.fa" # "/.mounts/labs/simpsonlab/users/dsokolowski/projects/GenomeAnnotationTutorial/data/references/mmus_GRC39/GCF_000001635.27_GRCm39_genomic.fna" # directory in /data -- adding species can be done with scripts in /utils
refTogaBed: "Reference-annotation.bed" # "/.mounts/labs/simpsonlab/users/dsokolowski/projects/GenomeAnnotationTutorial/data/references/mmus_GRC39/GCF_000001635.27_GRCm39_genomic.toga.bed"
refTogaIsoform: "reference-isoforms-file.tsv" # "/.mounts/labs/simpsonlab/users/dsokolowski/projects/GenomeAnnotationTutorial/data/references/mmus_GRC39/GCF_000001635.27_GRCm39_genomic.isoforms.toga.tsv"

refToga2: "none" # Use above format if you are using two reference species with TOGA
TogaDir2: "" # required to bind to singularity image
refTogaFa2: "" # directory in /data -- adding species can be done with scripts in /utils
refTogaBed2: ""
refTogaIsoform2: ""


refLiftOff: "LiftOff-Reference-prefix" # "NMR"
refLiftOffFa: "LiftOff-species-softmasked.fa" # "/.mounts/labs/simpsonlab/users/dsokolowski/projects/GenomeAnnotationTutorial/data/references/HetGlaV2_female/Heterocephalus_glaber_female.Naked_mole-rat_maternal.dna_sm.toplevel.fa" # directory in /data -- adding species can be done with scripts in /utils
refLiftOffGff:  "LiftOff-species-annotation.gffread.gff" # "/.mounts/labs/simpsonlab/users/dsokolowski/projects/GenomeAnnotationTutorial/data/references/HetGlaV2_female/Heterocephalus_glaber_female.Naked_mole-rat_maternal.113.gffread.gff" # directory in /data -- adding species can be done with scripts in /utils

orthofinderFA: "Reference_proteins.faa" # "/.mounts/labs/simpsonlab/users/dsokolowski/projects/GenomeAnnotationTutorial/data/references/mmus_GRC39/GCF_000001635.27_GRCm39_genomic.nostop.protein.faa" # directory name in ~/data
orthofinderTab: "Reference_proteinID_geneSymbol_key.txt" # "/.mounts/labs/simpsonlab/users/dsokolowski/projects/GenomeAnnotationTutorial/data/references/mmus_GRC39/GCF_000001635.27_GRCm39_genomic.table.txt" # directory name in ~/data

# Tool specific parameters
dfamDB: "rodentia" # change to a different repeatmasker class if desired, e.g., "arthropoda" for insects
brakerOdbFaa: "Vertebrata.fa" # change to a different odb12 protein set. e.g.,  "Arthropoda.fa" # https://bioinf.uni-greifswald.de/bioinf/partitioned_odb12/Arthropoda.fa.gz to get arthopods
mikadoScore: "mammalian.yaml" # Use a different scoring file for a different clade "HISTORIC/dmelanogaster_scoring.yaml"
mirmachineClade: "Mammalia" # "mirmachine-clade" # "Glires" 
