import glob
from pathlib import Path

rule all:
    input:
        config["outDir"]+"/full_annotation.geneSymbols.gff"

rule preprocess_data:
    input:
        assembly=config["assemblyFile"]
    output:
        assembly_out=config["outDir"] + "/assembly/assembly.fa"
    threads: 
        1
    params:
        memory_per_thread="8G",
        extra_cluster_opt="",
        walltime="2:00:00",

        source=config["sourceDir"],
        external=config["externalDir"],
        data=config["dataDir"],
        rnaseq=config["rnaseqDir"],
        isoseq=config["isoseqDir"],
        toga=config["TogaDir"],
        refTogaFa=config["refTogaFa"],
        refTogaBed=config["refTogaBed"],
        refTogaIsoform=config["refTogaIsoform"],
        refLiftOffFa=config["refLiftOffFa"],
        refLiftOffGff=config["refLiftOffGff"],
        orthofinderFA=config["orthofinderFA"],
        orthofinderTab=config["orthofinderTab"],
        brakerOdbFaa=config["brakerOdbFaa"],
        outDir=config["outDir"]
    shell:
        """
        echo "Running preflight check: "
        fail=0

        check_file() {{
            local file=$1
            local minsize=${{2:-0}}
            if [[ ! -f "$file" ]]; then
                echo "File not found: $file"
                fail=1
            elif [[ $minsize -gt 0 ]]; then
                size=$(stat -c%s "$file")
                if [[ $size -lt $minsize ]]; then
                    echo "File too small (<$minsize bytes): $file"
                    fail=1
                else
                    echo "File OK: $file"
                fi
            else
                echo "File OK: $file"
            fi
        }}

        check_dir() {{
            local dir=$1
            shift
            local required=("$@")
            if [[ ! -d "$dir" ]]; then
                echo "Directory not found: $dir"
                fail=1
                return
            fi
            echo "Directory OK: $dir"
            for r in "${{required[@]}}"; do
                if [[ ! -e "$dir/$r" ]]; then
                    echo "Missing: $dir/$r"
                    fail=1
                else
                    echo "Found: $dir/$r"
                fi
            done
        }}

        # Preflight checks
        check_file "{params.source}"
        check_dir "{params.external}" stringtie kent Augustus singularity_images TOGA infernal-tblout2gff.pl
        check_dir "{params.data}" braker_protein Rfam uniprot_sprot
        check_file "{input.assembly}" 1000000
        check_dir "{params.rnaseq}"
        check_dir "{params.isoseq}"
        check_dir "{params.toga}"
        check_file "{params.refTogaFa}" 1000000
        check_file "{params.refTogaBed}" 500000
        check_file "{params.refTogaIsoform}"
        check_file "{params.refLiftOffFa}" 1000000
        check_file "{params.refLiftOffGff}" 500000
        check_file "{params.orthofinderFA}" 500000
        check_file "{params.orthofinderTab}"
        check_file "{params.data}/braker_protein/{params.brakerOdbFaa}" 1000000

        echo "==============================="
        if [[ $fail -ne 0 ]]; then
            echo "Preflight check FAILED"
            exit 1
        else
            echo "Preflight check PASSED"
        fi

        echo "Make starting directory structure"
        cp {input.assembly} {output.assembly_out}
        samtools faidx {output.assembly_out}
        mkdir -p "{params.outDir}/transcript_selection"
        
        """

rule copy_RNAseq: 
    input:
        assembly=config["outDir"]+"/assembly/assembly.fa",
        rnaseqDir=config["rnaseqDir"]
    output:
        directory(config["outDir"]+"/RNAseq_alignment")
    threads:
        1  # Request 16 threads for this rule
    params:
        memory_per_thread="8G",
        extra_cluster_opt="",
        walltime="20:00:00"
    shell:
        """

        cp -r {input.rnaseqDir} {output}


        """

rule copy_ISOseq: 
    input:
        assembly=config["outDir"]+"/assembly/assembly.fa",
        isoseqDir=config["isoseqDir"]
    output:
        directory(config["outDir"]+"/ISOseq_alignment")
    threads:
        1  # Request 16 threads for this rule
    params:
        memory_per_thread="8G",
        extra_cluster_opt="",
        walltime="20:00:00"
    shell:
        """

        cp -r {input.isoseqDir} {output}


        """

rule merge_isoseq: 
    input:
        config["outDir"]+"/ISOseq_alignment"
    output:
        config["outDir"]+"/transcript_selection/merged.lr.bam.bai"
    threads:
        16
    params:
        memory_per_thread="8G",
        extra_cluster_opt="",
        walltime="100:00:00",
        outDir=config["outDir"]

    shell: 
        """

        if [[ $(ls {params.outDir}/ISOseq_alignment | wc -l) -gt 0  ]] ; then
            echo "we detected ISOseq data to merge"
            samtools merge -@ {threads} {params.outDir}/transcript_selection/merged.lr.tmp.bam {params.outDir}/ISOseq_alignment/*.bam

            samtools index -@ {threads} {params.outDir}/transcript_selection/merged.lr.tmp.bam

            samtools view -@ {threads} -b \
                {params.outDir}/transcript_selection/merged.lr.tmp.bam \
                $(cut -f1 {params.outDir}/assembly/assembly.fa.fai | tr '\n' ' ') \
                > {params.outDir}/transcript_selection/merged.lr.bam

            samtools index -@ {threads} {params.outDir}/transcript_selection/merged.lr.bam

            rm {params.outDir}/transcript_selection/merged.lr.tmp.bam

        else
            echo "No IOSeq data was detected"
            touch {output}
        fi
        """

rule merge_rnaseq: 
    input:
        config["outDir"]+"/RNAseq_alignment"
    output:
        config["outDir"]+"/transcript_selection/merged.sr.bam.bai"
    threads:
        16
    params:
        memory_per_thread="8G",
        extra_cluster_opt="",
        walltime="100:00:00",
        outDir=config["outDir"]

    shell: 
        """
        if [[ $(ls {params.outDir}/RNAseq_alignment | wc -l) -gt 0  ]] ; then
            echo "we detected RNAseq data to merge"
            samtools merge -@ {threads} {params.outDir}/transcript_selection/merged.sr.tmp.bam {params.outDir}/RNAseq_alignment/*.bam

            samtools index -@ {threads} {params.outDir}/transcript_selection/merged.sr.tmp.bam

            samtools view -@ {threads} -b \
                {params.outDir}/transcript_selection/merged.sr.tmp.bam \
                $(cut -f1 {params.outDir}/assembly/assembly.fa.fai | tr '\n' ' ') \
                > {params.outDir}/transcript_selection/merged.sr.bam

            samtools index -@ {threads} {params.outDir}/transcript_selection/merged.sr.bam

            rm {params.outDir}/transcript_selection/merged.sr.tmp.bam

        else
            echo "no RNAseq data was detected"
            touch {output}
        fi
        """


# run earl grey or copy masked data

rule mask_assembly:
    input:
        config["outDir"]+"/assembly/assembly.fa"
    output:
        config["outDir"]+"/assembly/assembly.softmasked.fa"
    threads:
        28
    params:
        memory_per_thread="8G",
        extra_cluster_opt="",
        walltime="150:00:00",

        outDir=config["outDir"],
        externalDir=config["externalDir"],
        species=config["species"],
        MaskedAssemblyFile=config["MaskedAssemblyFile"],
        MaskedAssemblyAnnotation=config["MaskedAssemblyAnnotation"],
        dfamDB=config["dfamDB"]
    shell:
        """
        scripts/run_earl_grey.sh {params.outDir} {params.externalDir} {params.species} {params.MaskedAssemblyFile} {params.MaskedAssemblyAnnotation} {params.dfamDB} {threads} 

        """

##
### Find Gene models
##

# custom GFF

rule process_custom_gff: # question: do we need the params in params if we go straight into shell?
    input:
        config["outDir"]+"/assembly/assembly.fa"
    output:
        config["outDir"]+"/transcript_selection/custom.gffread.gff"
    threads:
        1  # Request 16 threads for this rule
    params:
        memory_per_thread="8G",
        extra_cluster_opt="",
        walltime="2:00:00",

        customGFF=config["customGFF"]
    shell:
        """
        if [[ {params.customGFF} != "none" ]] ; then 
            echo "We detected a custom gff file"

            gffread {params.customGFF} --keep-genes -o {output}
        else

            echo "We did not detect a custom gff"
            touch {output}

        fi
        """

rule transcript_asm_stringtie: 
    input:
        config["outDir"]+"/assembly/assembly.fa",
        config["outDir"]+"/RNAseq_alignment",
        config["outDir"]+"/ISOseq_alignment"
    output:
        config["outDir"]+"/transcript_selection/stringtie.gffread.gff"
    threads:
        16
    params:
        memory_per_thread="8G",
        extra_cluster_opt="",
        walltime="100:00:00",

        outDir=config["outDir"],
        externalDir=config["externalDir"],
        rnaseqCov=config["rnaseqCov"],
        isoseqCov=config["isoseqCov"],
        stringtieMerge=config["stringtieMerge"],
        customStringtie=config["customStringtie"]

    shell: 
        """


       if [[ {params.customStringtie} = "none" ]] ; then 
            
            scripts/run_stringtie_flexible.sh {params.outDir} {params.externalDir} {workflow.basedir} {threads} {params.rnaseqCov} {params.isoseqCov} {params.stringtieMerge}

        else

            echo "Converting your custom transcript assembly to input for mikado. Skipping StringTie"

            gffread {params.customStringtie} --keep-genes -o {output}

        fi

        """

# liftOff

rule liftoff_asm: 
    input:
        config["outDir"]+"/assembly/assembly.fa"
    output:
        config["outDir"]+"/transcript_selection/liftoff.gffread.gff"
    threads:
        16
    params:
        memory_per_thread="4G",
        extra_cluster_opt="",
        walltime="60:00:00",

        outDir=config["outDir"],
        refLiftOffGff=config["refLiftOffGff"],
        refLiftOffFa=config["refLiftOffFa"],
        customLiftoff=config["customLiftoff"]

    shell: 
        """
        if [[ {params.customLiftoff} = "none" ]] ; then 

            cd {params.outDir}

            mkdir -p liftoff

            cd liftoff

            gffutils-cli create {params.refLiftOffGff} -o referencegff_db

            liftoff -db referencegff_db {input} {params.refLiftOffFa} -o ./liftoff.gff -u ./unmapped.liftoff.txt -copies

            gffread ./liftoff.gff --keep-genes -o {output}

        else
            echo "Converting your custom liftoff/lifton assembly to input for mikado. Skipping liftoff"

            gffread {params.customLiftoff} --keep-genes -o {output}

        fi
        """

rule braker_noRNA: 
    input:
        config["outDir"]+"/assembly/assembly.softmasked.fa",
        config["outDir"]+"/RNAseq_alignment",
        config["outDir"]+"/ISOseq_alignment"
    output:
        config["outDir"]+"/transcript_selection/braker.noRNA.gffread.gff"
    threads:
        28
    params:
        memory_per_thread="12G",
        extra_cluster_opt="",
        walltime="200:00:00",

        outDir=config["outDir"],
        externalDir=config["externalDir"],
        target=config["target"],
        dataDir=config["dataDir"],
        brakerOdbFaa=config["brakerOdbFaa"],
        customBraker=config["customBraker"]

    shell: 
        """
        if [[ {params.customBraker} = "none" ]] ; then 
        
            if [[ $(ls {params.outDir}/RNAseq_alignment | wc -l) -eq 0 && $(ls {params.outDir}/ISOseq_alignment | wc -l) -eq 0 ]] ; then

                echo "We did not find short read or long read RNA-seq data (aligned bam files)"

                scripts/run_braker_noRNAseq.sh {params.outDir} {params.externalDir} {params.target} {params.dataDir} {params.brakerOdbFaa} {threads}

                touch {params.outDir}/transcript_selection/braker.sr.gffread.gff # dummy variable for later
                touch {params.outDir}/transcript_selection/braker.lr.gffread.gff # dummy variable for later
            else

                touch {output}

            fi

        else
            echo "You put a custom output for braker. Skipping step"
            touch {output}
        fi



        """

rule braker_sr: 
    input:
        config["outDir"]+"/assembly/assembly.softmasked.fa",
        config["outDir"]+"/RNAseq_alignment",
        config["outDir"]+"/ISOseq_alignment"
    output:
        config["outDir"]+"/transcript_selection/braker.sr.gffread.gff"
    threads:
        28
    params:
        memory_per_thread="12G",
        extra_cluster_opt="",
        walltime="200:00:00",

        outDir=config["outDir"],
        externalDir=config["externalDir"],
        target=config["target"],
        dataDir=config["dataDir"],
        brakerOdbFaa=config["brakerOdbFaa"],
        stranded=config["stranded"],
        customBraker=config["customBraker"]

    shell: 
        """
        if [[ {params.customBraker} = "none" ]] ; then 

            if [[ $(ls {params.outDir}/RNAseq_alignment | wc -l) -gt 0 ]] ; then
                echo "We detected short read RNAseq"
                if [[ {params.stranded} = "TRUE" ]] ; then 
                    echo "You reported that RNAseq is stranded"
                    scripts/make_RNAseq_stranded.sh {params.outDir} {threads} 
                    scripts/run_braker_stranded.sh {params.outDir} {params.externalDir} {params.target} {params.dataDir} {params.brakerOdbFaa} {threads}
                else
                    scripts/run_braker_sr.sh {params.outDir} {params.externalDir} {params.target} {params.dataDir} {params.brakerOdbFaa} {threads}
    	    fi
            else
                touch {output}

            fi
        else
            echo "You put a custom output for braker. converting custom GFF to input for stringtie"
            gffread {params.customBraker} --keep-genes -o {output}
        fi
        """

rule braker_lr: 
    input:
        config["outDir"]+"/assembly/assembly.softmasked.fa",
        config["outDir"]+"/RNAseq_alignment",
        config["outDir"]+"/ISOseq_alignment"
    output:
        config["outDir"]+"/transcript_selection/braker.lr.gffread.gff"
    threads:
        28
    params:
        memory_per_thread="12G",
        extra_cluster_opt="",
        walltime="200:00:00",

        outDir=config["outDir"],
        externalDir=config["externalDir"],
        target=config["target"],
        dataDir=config["dataDir"],
        brakerOdbFaa=config["brakerOdbFaa"],
        customBraker=config["customBraker"]
    shell: 
        """
        if [[ {params.customBraker} = "none" ]] ; then 
            if [[ $(ls {params.outDir}/ISOseq_alignment | wc -l) -gt 0 ]] ; then
                echo "We detected ISOseq"
                scripts/run_braker_lr.sh {params.outDir} {params.externalDir} {params.target} {params.dataDir} {params.brakerOdbFaa} {threads}
            else
                touch {output}
            fi
        else
            touch {output}
        fi
        """

rule cactus_anno:
    input:
        config["outDir"]+"/assembly/assembly.softmasked.fa"
    output:
        config["outDir"]+"/cactus_alnr1/target-to-ref.chain"
    threads:
        32
    params:
        memory_per_thread="12G",
        extra_cluster_opt="",
        walltime="200:00:00",

        outDir=config["outDir"],
        externalDir=config["externalDir"],
        target=config["target"],
        TogaDir=config["TogaDir"],
        refToga=config["refToga"],
        refTogaFa=config["refTogaFa"],
        customTOGA=config["customTOGA"]
    shell: 
        """
       if [[ {params.customTOGA} = "none" ]] ; then 
            scripts/make_cactus_tree.sh {params.outDir} {params.target} {params.refToga} {params.refTogaFa} "r1"
            scripts/cactus_align_and_chain_sif.sh {params.outDir} {params.externalDir} {params.TogaDir} {params.target} {params.refToga} "r1"
        else
            echo "Skipping cactus for reference species 1 as you provided custom TOGA gff"
            touch {output}
        fi
        """

rule toga_anno:
    input:
        config["outDir"]+"/cactus_alnr1/target-to-ref.chain"
    output:
        config["outDir"]+"/transcript_selection/toga.r1.gffread.gff"
    threads:
        32
    params:
        memory_per_thread="12G",
        extra_cluster_opt="",
        walltime="72:00:00",

        outDir=config["outDir"],
        externalDir=config["externalDir"],       
        target=config["target"], 
        refToga=config["refToga"],
        refTogaBed=config["refTogaBed"],
        refTogaIsoform=config["refTogaIsoform"],
        customTOGA=config["customTOGA"]
    shell: 
        """
        
        if [[ {params.customTOGA} = "none" ]] ; then 
            scripts/run_toga.sh {params.outDir} {params.externalDir} {params.target} {params.refToga} {params.refTogaBed} {params.refTogaIsoform} "r1"
        else
            echo "Converting custom toga GFF into input for mikado"
            gffread {params.customTOGA} --keep-genes -o {output}

        fi
        """


rule cactus_anno2:
    input:
        config["outDir"]+"/assembly/assembly.softmasked.fa"
    output:
        config["outDir"]+"/cactus_alnr2/target-to-ref.chain"
    threads:
        32
    params:
        memory_per_thread="12G",
        extra_cluster_opt="",
        walltime="200:00:00",

        outDir=config["outDir"],
        externalDir=config["externalDir"],
        target=config["target"],
        TogaDir2=config["TogaDir2"],
        refToga2=config["refToga2"],
        refTogaFa2=config["refTogaFa2"],
        customTOGA2=config["customTOGA2"]
    shell: 
        """
        if [[ {params.customTOGA2} = "none" ]] ; then 
            if [ "{params.refToga2}" != "none" ] ; then
                scripts/make_cactus_tree.sh {params.outDir} {params.target} {params.refToga2} {params.refTogaFa2} "r2"
                scripts/cactus_align_and_chain_sif.sh {params.outDir} {params.externalDir} {params.TogaDir2} {params.target} {params.refToga2} "r2"
            else
                touch {output}
            fi
        else
            echo "Skipping cactus for reference species 2 as you provided custom TOGA (species 2) gff"
            touch {output}
        fi
        """

rule toga_anno2:
    input:
        config["outDir"]+"/cactus_alnr2/target-to-ref.chain"
    output:
        config["outDir"]+"/transcript_selection/toga.r2.gffread.gff"
    threads:
        32
    params:
        memory_per_thread="12G",
        extra_cluster_opt="",
        walltime="72:00:00",

        outDir=config["outDir"],
        externalDir=config["externalDir"],       
        target=config["target"], 
        refToga2=config["refToga2"],
        refTogaBed2=config["refTogaBed2"],
        refTogaIsoform2=config["refTogaIsoform2"],
        customTOGA2=config["customTOGA2"]
    shell: 
        """
        if [[ {params.customTOGA2} = "none" ]] ; then 
            if [ "{params.refToga2}" != "none" ] ; then
                scripts/run_toga.sh {params.outDir} {params.externalDir} {params.target} {params.refToga2} {params.refTogaBed2} {params.refTogaIsoform2} "r2"
            else
                touch {output}
            fi
        else
            echo "Converting custom toga (species2) GFF into input for mikado"
            gffread {params.customTOGA2} --keep-genes -o {output}
        fi
        """

rule mikado_prepare:
    input:
        config["outDir"]+"/assembly/assembly.softmasked.fa",
        config["outDir"]+"/transcript_selection/custom.gffread.gff",
        config["outDir"]+"/transcript_selection/stringtie.gffread.gff",
        config["outDir"]+"/transcript_selection/liftoff.gffread.gff",
        config["outDir"]+"/transcript_selection/braker.noRNA.gffread.gff",
        config["outDir"]+"/transcript_selection/braker.sr.gffread.gff",        
        config["outDir"]+"/transcript_selection/braker.lr.gffread.gff",
        config["outDir"]+"/transcript_selection/toga.r1.gffread.gff",
        config["outDir"]+"/transcript_selection/toga.r2.gffread.gff"
    output:
        config["outDir"]+"/transcript_selection/mikado_prepared.fasta.fai"
    threads:
        1
    params:
        memory_per_thread="12G",
        extra_cluster_opt="",
        walltime="2:00:00",

        outDir=config["outDir"],
        externalDir=config["externalDir"],
        customRef=config["customRef"],
        liftoffRef=config["liftoffRef"],
        mikadoScore=config["mikadoScore"]
    shell: 
        """
            scripts/12_mikado_configure_and_prepare.sh {params.outDir} {params.externalDir} {params.customRef} {params.liftoffRef} {workflow.basedir} {params.mikadoScore} {threads}
        """

rule transdecoder:
    input:
        config["outDir"]+"/transcript_selection/mikado_prepared.fasta.fai"
    output:
        config["outDir"]+"/transcript_selection/transdecoder/transdecoder/mikado_prepared.fasta.transdecoder.bed"
    threads:
        8
    params:
        memory_per_thread="12G",
        extra_cluster_opt="",
        walltime="48:00:00",

        outDir=config["outDir"]
    shell: 
        """
            mkdir -p {params.outDir}/transcript_selection/transdecoder

            cd {params.outDir}/transcript_selection/transdecoder

            TransDecoder.LongOrfs -t {params.outDir}/transcript_selection/mikado_prepared.fasta -m 100 -O "transdecoder"
            TransDecoder.Predict -t {params.outDir}/transcript_selection/mikado_prepared.fasta --retain_long_orfs_length 100 -O "transdecoder"
        """


rule junctions:
    input:
        config["outDir"]+"/transcript_selection/mikado_prepared.fasta.fai",
        config["outDir"]+"/transcript_selection/merged.sr.bam.bai",
        config["outDir"]+"/transcript_selection/merged.lr.bam.bai"
    output:
        config["outDir"]+"/transcript_selection/junctions.final.bed"
    threads:
        16
    params:
        memory_per_thread="12G",
        extra_cluster_opt="",
        walltime="48:00:00",
        outDir=config["outDir"]
    shell: 
        """
            scripts/get_junctions.sh {params.outDir} {threads}
        """

rule split_fasta:
    input:
        config["outDir"]+"/transcript_selection/mikado_prepared.fasta.fai"
    output:
        expand("{outDir}/transcript_selection/blast/output_{split_id}.fasta", split_id = range(1, 100), outDir=config["outDir"])
    threads:
        1
    params:
        memory_per_thread="12G",
        extra_cluster_opt="",
        walltime="48:00:00",

        outDir=config["outDir"]
    shell:
        """

        mkdir -p {params.outDir}/transcript_selection/blast

        cp {params.outDir}/transcript_selection/mikado_prepared.fasta {params.outDir}/transcript_selection/blast

        scripts/splitfa.sh mikado_prepared.fasta 100 {params.outDir}
        
        rm {params.outDir}/transcript_selection/blast/mikado_prepared.fasta

        """

rule blastp_run:
    input:
        config["outDir"]+"/transcript_selection/blast/output_{split_id}.fasta"
    output:
        config["outDir"]+"/transcript_selection/blast/output_{split_id}/blast_done.txt"
        
    threads:
        4
    params:
        memory_per_thread="8G",
        extra_cluster_opt="",
        walltime="48:00:00",

        outDir=config["outDir"],
        dataDir=config["dataDir"]
    shell: 
        """

        cd {params.dataDir}/uniprot_sprot
        
        blastx -max_target_seqs 5 -num_threads {threads} -query {input} \
        -outfmt "6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore ppos btop" \
        -db {params.dataDir}/uniprot_sprot/uniprot_sprot_nodup.fasta -evalue 0.000001 \
        -out {params.outDir}/transcript_selection/blast/output_{wildcards.split_id}/blast_results.tsv
        

        touch {output}
        

        """

rule serialize_pick:
    input:
        config["outDir"]+"/transcript_selection/mikado_prepared.fasta.fai",
        expand("{outDir}/transcript_selection/blast/output_{split_id}/blast_done.txt", split_id = range(1, 100), outDir=config["outDir"]),
        config["outDir"]+"/transcript_selection/junctions.final.bed",
        config["outDir"]+"/transcript_selection/transdecoder/transdecoder/mikado_prepared.fasta.transdecoder.bed"
    output:
        config["outDir"]+"/transcript_selection/mikado_lenient.faa"
    threads:
        4
    params:
        memory_per_thread="12G",
        extra_cluster_opt="",
        walltime="48:00:00",
        outDir=config["outDir"],
        dataDir=config["dataDir"],
        externalDir=config["externalDir"]
    shell:
        """
        scripts/45_mikado_serialize_pick.sh {params.outDir} {params.dataDir} {params.externalDir} {threads}
        """

rule run_orthofinder:
    input:
        config["outDir"]+"/transcript_selection/mikado_lenient.faa",
    output:
        config["outDir"]+"/orthofinder/orthofinder_protein.tsv"
    threads:
        12
    params:
        memory_per_thread="12G",
        extra_cluster_opt="",
        walltime="64:00:00",

        outDir=config["outDir"],
        orthofinderTab=config["orthofinderTab"],
        orthofinderFA=config["orthofinderFA"],
        target=config["target"]
    shell:
        """
        
        cd {params.outDir}

        mkdir -p orthofinder

        cd orthofinder

        ln -s {params.outDir}/transcript_selection/mikado_lenient.gff ./

        echo "GFF3 file: mikado_lenient.gff"
        echo "Name of gene list out: mikado_lenient.txt"

        grep -P "\tgene\t" mikado_lenient.gff > mikado_lenient.txt
        sed -i 's/.*ID=\(.*\);Name.*/\1/' mikado_lenient.txt

        ln -s {params.orthofinderTab} ./

        mkdir -p protein_seqs

        cd protein_seqs 
        
        cp {params.orthofinderFA} ./
        cp {input} ./

	sed -i '/^>/! s/\./X/g' mikado_lenient.faa


        cd ../

        date_orthofinder=$(date +"%b%d")
        filename=$(basename -- {params.orthofinderFA})
        noExtension=`basename $filename .faa`

        echo $date_orthofinder

        orthofinder -t {threads} -a {threads} -o {params.target}"_orthofinder" -f protein_seqs

        cp {params.outDir}/orthofinder/{params.target}"_orthofinder"/Results_$date_orthofinder/Orthologues/Orthologues_mikado_lenient/mikado_lenient__v__$noExtension.tsv orthofinder_protein.tsv

        """

rule mirmachine:
    input:
        config["outDir"]+"/assembly/assembly.softmasked.fa",
        config["outDir"]+"/transcript_selection/mikado_lenient.faa"
    output:
        config["outDir"]+"/mirmachine/mirna.filtered.gff"
    threads:
        20
    params:
        memory_per_thread="10G",
        extra_cluster_opt="",
        walltime="48:00:00",

        outDir=config["outDir"],
        mirmachineClade=config["mirmachineClade"],
        species=config["species"]

    shell:
        """

        cd {params.outDir}

        mkdir -p mirmachine ; cd mirmachine

	if [ "{params.mirmachineClade}" != "Skip" ] ; then

        ASSEMBLY={params.outDir}/assembly/assembly.softmasked.fa

        samtools faidx $ASSEMBLY

        MirMachine.py -n {params.mirmachineClade} -s {params.species} --genome $ASSEMBLY -m deutero --cpu {threads}
        
        cp {params.outDir}/mirmachine/results/predictions/filtered_gff/{params.species}.PRE.gff mirna.filtered.gff

	else
            touch {output}
        fi

        """

rule ncRNA_covariance:
    input:
        config["outDir"]+"/assembly/assembly.softmasked.fa",
        config["outDir"]+"/transcript_selection/mikado_lenient.faa"
    output:
        config["outDir"]+"/ncRNA_analysis/assembly.tblout"
    threads:
        20
    params:
        memory_per_thread="10G",
        extra_cluster_opt="",
        walltime="48:00:00",

        outDir=config["outDir"],
        dataDir=config["dataDir"]
    shell:
        """

        scripts/ncRNA_analysis.sh {params.outDir} {params.dataDir} {threads}


        """
rule full_annotation:
    input:
        config["outDir"]+"/mirmachine/mirna.filtered.gff",
        config["outDir"]+"/ncRNA_analysis/assembly.tblout"
    output:
        config["outDir"]+"/ncRNA_analysis/full_annotation.gff"
    threads:
        4
    params:
        memory_per_thread="10G",
        extra_cluster_opt="",
        walltime="24:00:00",

        outDir=config["outDir"],
        dataDir=config["dataDir"],
        externalDir=config["externalDir"]
    shell:
        """

        scripts/ncRNA_postprocess.sh {params.outDir} {params.dataDir} {params.externalDir} {workflow.basedir}

        """
    
rule aggregate_symbols:
    input:
        config["outDir"]+"/ncRNA_analysis/full_annotation.gff",
        config["outDir"]+"/orthofinder/orthofinder_protein.tsv"
    output:
        config["outDir"]+"/full_annotation.geneSymbols.gff"
    threads:
        4
    params:
        memory_per_thread="10G",
        extra_cluster_opt="",
        walltime="24:00:00",
        outDir=config["outDir"],
        orthofinderTab=config["orthofinderTab"],
        refTogaIsoform=config["refTogaIsoform"],
        refTogaIsoform2=config["refTogaIsoform2"],
        refToga2=config["refToga2"]
    shell:
        """

        scripts/aggregate_symbols.sh {params.outDir} {params.orthofinderTab} {workflow.basedir} {params.refTogaIsoform} {params.refTogaIsoform2} {params.refToga2}


        """

